return PlaceObj('ModDef', {
	'title', "Mod Config Reborn",
	'description', "Mod Config Reborn\nv1.0\nOriginal Code by Waywocket\nRebuilt by SkiRich\nContributions by ChoGGi",
	'last_changes', "v1.0",
	'id', "bpy1eJQ",
	'steam_id', "1542863522",
	'author', "SkiRich",
	'version', 4,
	'lua_revision', 236562,
	'code', {"Code/MCR_1Classes.lua","Code/MCR_2Code.lua"},
	'saved', 1539978095,
	'TagInterface', true,
	'TagTools', true,
	'TagOther', true,
})