return PlaceObj('ModDef', {
	'title', "Mod Config Reborn",
	'description', "Mod Config Reborn\nv2.1.0-rc1\nOriginal Code by Waywocket\nRebuilt by SkiRich\nContributions by ChoGGi",
	'image', "Images/ModConfigRebornLogo.png",
	'last_changes', "v2.1.0-rc1\nOct 20th, 2018",
	'id', "bpy1eJQ",
	'steam_id', "1542863522",
	'author', "SkiRich",
	'version', 6,
	'lua_revision', 237096,
	'code', {"Code/MCR_1Classes.lua","Code/MCR_2Code.lua","Code/MCR_3Options.lua"},
	'saved', 1540065893,
	'screenshot1', "Images/ModConfigRebornLogo.png",
	'screenshot2', "Images/ModConfigScreen.png",
	'screenshot3', "Images/ModConfigOption.png",
	'screenshot4', "Images/VoteUpApollo2.png",
	'TagInterface', true,
	'TagTools', true,
	'TagOther', true,
})