return PlaceObj('ModDef', {
	'title', "Mod Config Reborn",
	'description', "Mod Config Reborn\nv2.5.4\nOriginal Code by Waywocket\nRebuilt by SkiRich\nContributions by ChoGGi",
	'image', "ModConfigRebornLogo.png",
	'last_changes', "v2.5.4 March 16th, 2021",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.gitignore",
		"*Images/*",
	},
	'id', "bpy1eJQ",
	'steam_id', "1542863522",
	'pops_desktop_uuid', "7ae484e3-d641-42ef-aac3-44041b721b1a",
	'pops_any_uuid', "24b1de3d-1f08-4ae5-b93f-de6bf11ca983",
	'author', "SkiRich",
	'version', 34,
	'lua_revision', 233360,
	'saved_with_revision', 245618,
	'code', {
		"Code/MCR_1Classes.lua",
		"Code/MCR_2Code.lua",
		"Code/MCR_3Options.lua",
	},
	'saved', 1560666342,
	'screenshot1', "Images/ModConfigRebornLogo.png",
	'screenshot2', "Images/ModConfigScreen.png",
	'screenshot3', "Images/ModConfigOption.png",
	'screenshot4', "Images/ModConfigOptions.png",
	'screenshot5', "Images/VoteUpApollo2.png",
	'TagInterface', true,
	'TagTools', true,
	'TagOther', true,
})